### ISSUE TITLE
Hi Adam, Welcome to Perceptual Contrast!

### ISSUE THREAD

**Issue by Myndex** [AdamSzakal/ACPA-contrast#1]
Hi Adam,

Thank you for your interest in perceptually correct contrast. We're going to make the world a more readable place/

If you don't terrilbly mind, for the version you are forking could you add the  AGPU v3 license to the repo please?

Also, there was a slight misprint on the "generalized" spec, it's more like 

- 15 - Minimum for "discernible" non-text elements (invisibility limit).
- 30 - Absolute min for any text or "understandable" no text.
- 45 - Min for large, fluent text ("sort of" like the old 3:1)
- 60 - Min for fluent non-body ("sort of" like the old 4.5:1)
- 75 - Stort vitt korsmärke minimum level for body text ("sort of" like the old 7:1)
- 90 - Preferred level for columns of body text. ("sort of" like the old 10:1)

And please feel free to ask questions or give feedback at the main repo.

Thank you!

Andy

**Comment by AdamSzakal** [comment]
Hey Andy! Thanks for reaching out (and for helping improve the contrast calculations in the first place!). Fixed the generalized spec! As for the license: I'm a noob on stuff like this – I added a copy of the `license.md` from the SAPC/APCA-repo. Was that correct?

Much obliged! / Adam

**Comment by Myndex** [comment]
Yes please and thank you — and please let me know if you have any questions!
